# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto clock in

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 17 * * *'
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: 'signin'
      env:
        USERNAME: ${{ secrets.2017010186 }}
        PASSWORD: ${{ secrets.08160013 }}
        AREA: ${{ secrets.北京市 海淀区 }}
        PROVINCE: ${{ secrets.北京市 }}
        CITY: ${{ secrets.北京市 }}
        SFZX: ${{ secrets.1 }}
      run: python auto.py

